use std::collections::{BTreeMap, BTreeSet};

use pine_builtins::{BuiltinHistoryRequirement, BuiltinSeriesHistoryRequirement};

const RUNTIME_DISPATCHED_CALLS: &[&str] = &[
    "alert",
    "alertcondition",
    "array.abs",
    "array.avg",
    "array.binary_search",
    "array.binary_search_leftmost",
    "array.binary_search_rightmost",
    "array.clear",
    "array.concat",
    "array.copy",
    "array.covariance",
    "array.every",
    "array.fill",
    "array.first",
    "array.from",
    "array.get",
    "array.includes",
    "array.indexof",
    "array.insert",
    "array.join",
    "array.last",
    "array.lastindexof",
    "array.max",
    "array.median",
    "array.min",
    "array.mode",
    "array.new_bool",
    "array.new_box",
    "array.new_color",
    "array.new_float",
    "array.new_int",
    "array.new_label",
    "array.new_line",
    "array.new_linefill",
    "array.new_polyline",
    "array.new<chart.point>",
    "array.new_string",
    "array.new_table",
    "array.percentile_linear_interpolation",
    "array.percentile_nearest_rank",
    "array.percentrank",
    "array.pop",
    "array.push",
    "array.range",
    "array.remove",
    "array.reverse",
    "array.set",
    "array.shift",
    "array.size",
    "array.slice",
    "array.some",
    "array.sort",
    "array.sort_indices",
    "array.standardize",
    "array.stdev",
    "array.sum",
    "array.unshift",
    "array.variance",
    "barcolor",
    "bgcolor",
    "bool",
    "chart.point.copy",
    "chart.point.from_index",
    "chart.point.from_time",
    "chart.point.new",
    "chart.point.now",
    "box",
    "box.copy",
    "box.delete",
    "box.get_bottom",
    "box.get_left",
    "box.get_right",
    "box.get_top",
    "box.new",
    "box.set_bgcolor",
    "box.set_border_color",
    "box.set_border_style",
    "box.set_border_width",
    "box.set_bottom_right_point",
    "box.set_bottom",
    "box.set_extend",
    "box.set_left",
    "box.set_lefttop",
    "box.set_right",
    "box.set_rightbottom",
    "box.set_top_left_point",
    "box.set_xloc",
    "box.set_text",
    "box.set_text_color",
    "box.set_text_font_family",
    "box.set_text_formatting",
    "box.set_text_halign",
    "box.set_text_size",
    "box.set_text_valign",
    "box.set_text_wrap",
    "box.set_top",
    "color",
    "color.b",
    "color.from_gradient",
    "color.g",
    "color.new",
    "color.r",
    "color.rgb",
    "color.t",
    "dayofmonth",
    "dayofweek",
    "fill",
    "fixnan",
    "float",
    "hline",
    "hour",
    "indicator",
    "max_bars_back",
    "input",
    "input.bool",
    "input.color",
    "input.float",
    "input.int",
    "input.price",
    "input.session",
    "input.source",
    "input.string",
    "input.symbol",
    "input.text_area",
    "input.time",
    "input.timeframe",
    "int",
    "label",
    "label.copy",
    "label.delete",
    "label.get_text",
    "label.get_x",
    "label.get_y",
    "label.new",
    "label.set_color",
    "label.set_size",
    "label.set_style",
    "label.set_text",
    "label.set_textalign",
    "label.set_text_font_family",
    "label.set_text_formatting",
    "label.set_textcolor",
    "label.set_tooltip",
    "label.set_point",
    "label.set_x",
    "label.set_xloc",
    "label.set_xy",
    "label.set_y",
    "label.set_yloc",
    "line",
    "line.copy",
    "line.delete",
    "line.get_price",
    "line.get_x1",
    "line.get_x2",
    "line.get_y1",
    "line.get_y2",
    "line.new",
    "line.set_color",
    "line.set_extend",
    "line.set_first_point",
    "line.set_second_point",
    "line.set_style",
    "line.set_width",
    "line.set_x1",
    "line.set_x2",
    "line.set_xloc",
    "line.set_xy1",
    "line.set_xy2",
    "line.set_y1",
    "line.set_y2",
    "linefill",
    "linefill.delete",
    "linefill.get_line1",
    "linefill.get_line2",
    "linefill.new",
    "linefill.set_color",
    "map.size",
    "matrix.add_col",
    "matrix.add_row",
    "matrix.avg",
    "matrix.columns",
    "matrix.concat",
    "matrix.col",
    "matrix.copy",
    "matrix.det",
    "matrix.diff",
    "matrix.eigenvalues",
    "matrix.eigenvectors",
    "matrix.elements_count",
    "matrix.fill",
    "matrix.get",
    "matrix.is_antidiagonal",
    "matrix.is_antisymmetric",
    "matrix.is_binary",
    "matrix.is_diagonal",
    "matrix.is_identity",
    "matrix.is_symmetric",
    "matrix.is_square",
    "matrix.is_stochastic",
    "matrix.is_triangular",
    "matrix.is_zero",
    "matrix.inv",
    "matrix.kron",
    "matrix.mult",
    "matrix.max",
    "matrix.median",
    "matrix.min",
    "matrix.mode",
    "matrix.new<float>",
    "matrix.new<int>",
    "matrix.new<bool>",
    "matrix.new<string>",
    "matrix.new<color>",
    "matrix.pinv",
    "matrix.pow",
    "matrix.rank",
    "matrix.remove_col",
    "matrix.remove_row",
    "matrix.reverse",
    "matrix.reshape",
    "matrix.row",
    "matrix.rows",
    "matrix.set",
    "matrix.sort",
    "matrix.submatrix",
    "matrix.swap_columns",
    "matrix.swap_rows",
    "matrix.sum",
    "matrix.trace",
    "matrix.transpose",
    "polyline",
    "polyline.delete",
    "polyline.new",
    "runtime.error",
    "math.abs",
    "math.acos",
    "math.asin",
    "math.atan",
    "math.avg",
    "math.cbrt",
    "math.ceil",
    "math.cos",
    "math.exp",
    "math.floor",
    "math.hypot",
    "math.log",
    "math.log10",
    "math.max",
    "math.min",
    "math.pow",
    "math.random",
    "math.round",
    "math.round_to_mintick",
    "math.sign",
    "math.sin",
    "math.sqrt",
    "math.sum",
    "math.tan",
    "math.todegrees",
    "math.toradians",
    "math.trunc",
    "minute",
    "month",
    "na",
    "nz",
    "plot",
    "plotarrow",
    "plotbar",
    "plotcandle",
    "plotchar",
    "plotshape",
    "request.security",
    "request.security_lower_tf",
    "second",
    "str.contains",
    "str.endswith",
    "str.format",
    "str.format_time",
    "str.length",
    "str.lower",
    "str.match",
    "str.pos",
    "str.repeat",
    "str.replace",
    "str.replace_all",
    "str.split",
    "str.startswith",
    "str.substring",
    "str.tonumber",
    "str.tostring",
    "str.trim",
    "str.upper",
    "syminfo.prefix",
    "syminfo.ticker",
    "ticker.heikinashi",
    "ticker.inherit",
    "ticker.kagi",
    "ticker.linebreak",
    "ticker.new",
    "ticker.modify",
    "ticker.pointfigure",
    "ticker.renko",
    "ticker.standard",
    "strategy",
    "strategy.close",
    "strategy.close_all",
    "strategy.cancel",
    "strategy.cancel_all",
    "strategy.convert_to_account",
    "strategy.convert_to_symbol",
    "strategy.default_entry_qty",
    "strategy.closedtrades.entry_bar_index",
    "strategy.closedtrades.entry_comment",
    "strategy.closedtrades.entry_id",
    "strategy.closedtrades.entry_price",
    "strategy.closedtrades.exit_bar_index",
    "strategy.closedtrades.exit_comment",
    "strategy.closedtrades.exit_id",
    "strategy.closedtrades.exit_price",
    "strategy.closedtrades.entry_time",
    "strategy.closedtrades.exit_time",
    "strategy.closedtrades.commission",
    "strategy.closedtrades.profit",
    "strategy.closedtrades.profit_percent",
    "strategy.closedtrades.size",
    "strategy.closedtrades.max_runup",
    "strategy.closedtrades.max_runup_percent",
    "strategy.closedtrades.max_drawdown",
    "strategy.closedtrades.max_drawdown_percent",
    "strategy.opentrades.entry_bar_index",
    "strategy.opentrades.entry_comment",
    "strategy.opentrades.entry_id",
    "strategy.opentrades.entry_price",
    "strategy.opentrades.entry_time",
    "strategy.opentrades.size",
    "strategy.opentrades.profit",
    "strategy.opentrades.profit_percent",
    "strategy.opentrades.commission",
    "strategy.opentrades.max_runup",
    "strategy.opentrades.max_runup_percent",
    "strategy.opentrades.max_drawdown",
    "strategy.opentrades.max_drawdown_percent",
    "strategy.entry",
    "strategy.order",
    "strategy.exit",
    "strategy.risk.allow_entry_in",
    "strategy.risk.max_cons_loss_days",
    "strategy.risk.max_drawdown",
    "strategy.risk.max_intraday_filled_orders",
    "strategy.risk.max_intraday_loss",
    "strategy.risk.max_position_size",
    "string",
    "ta.alma",
    "ta.ao",
    "ta.atr",
    "ta.barssince",
    "ta.bb",
    "ta.bbw",
    "ta.bop",
    "ta.cci",
    "ta.change",
    "ta.cmo",
    "ta.cog",
    "ta.correlation",
    "ta.covariance",
    "ta.cross",
    "ta.crossover",
    "ta.crossunder",
    "ta.cum",
    "ta.dema",
    "ta.dev",
    "ta.dmi",
    "ta.ema",
    "ta.falling",
    "ta.highest",
    "ta.highestbars",
    "ta.hma",
    "ta.kc",
    "ta.kcw",
    "ta.linreg",
    "ta.lowest",
    "ta.lowestbars",
    "ta.macd",
    "ta.max",
    "ta.median",
    "ta.mfi",
    "ta.min",
    "ta.mode",
    "ta.mom",
    "ta.percentile_linear_interpolation",
    "ta.percentile_nearest_rank",
    "ta.percentrank",
    "ta.pivot_point_levels",
    "ta.pivothigh",
    "ta.pivotlow",
    "ta.range",
    "ta.rci",
    "ta.rising",
    "ta.rma",
    "ta.roc",
    "ta.rsi",
    "ta.sar",
    "ta.sma",
    "ta.stdev",
    "ta.stoch",
    "ta.supertrend",
    "ta.swma",
    "ta.tema",
    "ta.tr",
    "ta.tsi",
    "ta.valuewhen",
    "ta.variance",
    "ta.vwap",
    "ta.vwma",
    "ta.wma",
    "ta.wpr",
    "table",
    "table.clear",
    "table.cell",
    "table.cell_set_bgcolor",
    "table.cell_set_height",
    "table.cell_set_text",
    "table.cell_set_text_color",
    "table.cell_set_text_halign",
    "table.cell_set_text_size",
    "table.cell_set_text_valign",
    "table.cell_set_text_wrap",
    "table.cell_set_text_font_family",
    "table.cell_set_text_formatting",
    "table.cell_set_tooltip",
    "table.cell_set_width",
    "table.delete",
    "table.merge_cells",
    "table.new",
    "table.set_border_color",
    "table.set_border_width",
    "table.set_bgcolor",
    "table.set_frame_color",
    "table.set_frame_width",
    "table.set_position",
    "time",
    "time_close",
    "timeframe.change",
    "timeframe.from_seconds",
    "timeframe.in_seconds",
    "timestamp",
    "weekofyear",
    "year",
];

const HISTORY_CLOSE_1: &[BuiltinSeriesHistoryRequirement] = &[BuiltinSeriesHistoryRequirement {
    symbol: "close",
    offset: 1,
}];

const HISTORY_DMI: &[BuiltinSeriesHistoryRequirement] = &[
    BuiltinSeriesHistoryRequirement {
        symbol: "high",
        offset: 1,
    },
    BuiltinSeriesHistoryRequirement {
        symbol: "low",
        offset: 1,
    },
    BuiltinSeriesHistoryRequirement {
        symbol: "close",
        offset: 1,
    },
];

const HISTORY_SAR: &[BuiltinSeriesHistoryRequirement] = &[
    BuiltinSeriesHistoryRequirement {
        symbol: "high",
        offset: 2,
    },
    BuiltinSeriesHistoryRequirement {
        symbol: "low",
        offset: 2,
    },
    BuiltinSeriesHistoryRequirement {
        symbol: "close",
        offset: 1,
    },
];

const RUNTIME_TA_IMPLICIT_HISTORY_CALLS: &[(&str, BuiltinHistoryRequirement)] = &[
    (
        "ta.tr",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_CLOSE_1),
    ),
    (
        "ta.atr",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_CLOSE_1),
    ),
    (
        "ta.supertrend",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_CLOSE_1),
    ),
    (
        "ta.kc",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_CLOSE_1),
    ),
    (
        "ta.kcw",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_CLOSE_1),
    ),
    (
        "ta.dmi",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_DMI),
    ),
    (
        "ta.sar",
        BuiltinHistoryRequirement::BuiltinSeries(HISTORY_SAR),
    ),
    (
        "ta.mfi",
        BuiltinHistoryRequirement::SourceOffset {
            source_arg: 0,
            offset: 1,
        },
    ),
    (
        "ta.tsi",
        BuiltinHistoryRequirement::SourceOffset {
            source_arg: 0,
            offset: 1,
        },
    ),
    (
        "ta.cmo",
        BuiltinHistoryRequirement::SourceOffset {
            source_arg: 0,
            offset: 1,
        },
    ),
    (
        "ta.change",
        BuiltinHistoryRequirement::OptionalLengthOffset {
            source_arg: 0,
            length_arg: 1,
            default_offset: 1,
        },
    ),
    (
        "ta.mom",
        BuiltinHistoryRequirement::RequiredLengthOffset {
            source_arg: 0,
            length_arg: 1,
        },
    ),
    (
        "ta.roc",
        BuiltinHistoryRequirement::RequiredLengthOffset {
            source_arg: 0,
            length_arg: 1,
        },
    ),
    (
        "ta.highest",
        BuiltinHistoryRequirement::WindowLengthOffset {
            source_arg: 0,
            length_arg: 1,
            default_source: Some("high"),
        },
    ),
    (
        "ta.lowest",
        BuiltinHistoryRequirement::WindowLengthOffset {
            source_arg: 0,
            length_arg: 1,
            default_source: Some("low"),
        },
    ),
    (
        "ta.highestbars",
        BuiltinHistoryRequirement::WindowLengthOffset {
            source_arg: 0,
            length_arg: 1,
            default_source: Some("high"),
        },
    ),
    (
        "ta.lowestbars",
        BuiltinHistoryRequirement::WindowLengthOffset {
            source_arg: 0,
            length_arg: 1,
            default_source: Some("low"),
        },
    ),
    (
        "ta.rising",
        BuiltinHistoryRequirement::RequiredLengthOffset {
            source_arg: 0,
            length_arg: 1,
        },
    ),
    (
        "ta.falling",
        BuiltinHistoryRequirement::RequiredLengthOffset {
            source_arg: 0,
            length_arg: 1,
        },
    ),
    (
        "ta.cross",
        BuiltinHistoryRequirement::Cross { args: 2, offset: 1 },
    ),
    (
        "ta.crossover",
        BuiltinHistoryRequirement::Cross { args: 2, offset: 1 },
    ),
    (
        "ta.crossunder",
        BuiltinHistoryRequirement::Cross { args: 2, offset: 1 },
    ),
];

#[test]
fn builtin_signatures_have_runtime_dispatch() {
    let runtime: BTreeSet<_> = RUNTIME_DISPATCHED_CALLS.iter().copied().collect();
    let registered: BTreeSet<_> = pine_builtins::PHASE_1_BUILTINS
        .iter()
        .map(|signature| signature.name)
        .collect();

    let missing_dispatch: Vec<_> = registered
        .iter()
        .copied()
        .filter(|name| !is_declaration_or_input(name))
        .filter(|name| !runtime.contains(name))
        .collect();
    assert!(
        missing_dispatch.is_empty(),
        "registered builtins missing runtime dispatch: {missing_dispatch:?}"
    );

    let unregistered_dispatch: Vec<_> = runtime
        .iter()
        .copied()
        .filter(|name| !is_declaration_or_input(name))
        .filter(|name| !registered.contains(name))
        .collect();
    assert!(
        unregistered_dispatch.is_empty(),
        "runtime dispatch names missing builtin signatures: {unregistered_dispatch:?}"
    );
}

#[test]
fn runtime_implicit_history_calls_match_shared_metadata() {
    let runtime_dispatch: BTreeSet<_> = RUNTIME_DISPATCHED_CALLS.iter().copied().collect();
    let reviewed_runtime_history: BTreeMap<_, _> =
        RUNTIME_TA_IMPLICIT_HISTORY_CALLS.iter().copied().collect();
    let shared_history: BTreeMap<_, _> = pine_builtins::BUILTIN_HISTORY_METADATA
        .iter()
        .map(|metadata| (metadata.name, metadata.requirement))
        .collect();
    assert_eq!(
        reviewed_runtime_history.len(),
        RUNTIME_TA_IMPLICIT_HISTORY_CALLS.len(),
        "reviewed runtime history call names must be unique"
    );
    assert_eq!(
        shared_history.len(),
        pine_builtins::BUILTIN_HISTORY_METADATA.len(),
        "shared builtin history metadata names must be unique"
    );

    let missing_dispatch: Vec<_> = reviewed_runtime_history
        .keys()
        .copied()
        .filter(|name| !runtime_dispatch.contains(name))
        .collect();
    assert!(
        missing_dispatch.is_empty(),
        "reviewed runtime history calls missing runtime dispatch: {missing_dispatch:?}"
    );

    assert_eq!(
        reviewed_runtime_history, shared_history,
        "runtime implicit-history review list must match shared builtin history metadata"
    );
}

fn is_declaration_or_input(name: &str) -> bool {
    matches!(name, "indicator" | "strategy" | "input") || name.starts_with("input.")
}
