//! Bind array operation names before executing bars.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub(crate) enum ArrayOpcode {
    NewFloat,
    NewInt,
    NewBool,
    NewString,
    NewColor,
    NewLine,
    NewLineFill,
    NewPolyline,
    NewLabel,
    NewBox,
    NewTable,
    NewChartPoint,
    NewUserType,
    From,
    Size,
    Push,
    Get,
    Set,
    Insert,
    Pop,
    Remove,
    Shift,
    Unshift,
    Fill,
    First,
    Last,
    Copy,
    Slice,
    Concat,
    Includes,
    Every,
    Some,
    IndexOf,
    LastIndexOf,
    BinarySearch,
    BinarySearchLeftmost,
    BinarySearchRightmost,
    Abs,
    Min,
    Max,
    Sum,
    Avg,
    Range,
    Median,
    Mode,
    PercentileNearestRank,
    PercentileLinearInterpolation,
    PercentRank,
    Covariance,
    Standardize,
    Variance,
    Stdev,
    Sort,
    SortIndices,
    Reverse,
    Join,
    Clear,
}

impl ArrayOpcode {
    pub(crate) fn for_name(callee: &str) -> Option<Self> {
        Some(match callee {
            "array.new_float" => Self::NewFloat,
            "array.new_int" => Self::NewInt,
            "array.new_bool" => Self::NewBool,
            "array.new_string" => Self::NewString,
            "array.new_color" => Self::NewColor,
            "array.new_line" => Self::NewLine,
            "array.new_linefill" => Self::NewLineFill,
            "array.new_polyline" => Self::NewPolyline,
            "array.new_label" => Self::NewLabel,
            "array.new_box" => Self::NewBox,
            "array.new_table" => Self::NewTable,
            "array.new<chart.point>" => Self::NewChartPoint,
            // Manual HIR has historically accepted every complete template
            // name here. The parser canonicalizes supported primitive names.
            _ if callee.starts_with("array.new<") && callee.ends_with('>') => Self::NewUserType,
            "array.from" => Self::From,
            "array.size" => Self::Size,
            "array.push" => Self::Push,
            "array.get" => Self::Get,
            "array.set" => Self::Set,
            "array.insert" => Self::Insert,
            "array.pop" => Self::Pop,
            "array.remove" => Self::Remove,
            "array.shift" => Self::Shift,
            "array.unshift" => Self::Unshift,
            "array.fill" => Self::Fill,
            "array.first" => Self::First,
            "array.last" => Self::Last,
            "array.copy" => Self::Copy,
            "array.slice" => Self::Slice,
            "array.concat" => Self::Concat,
            "array.includes" => Self::Includes,
            "array.every" => Self::Every,
            "array.some" => Self::Some,
            "array.indexof" => Self::IndexOf,
            "array.lastindexof" => Self::LastIndexOf,
            "array.binary_search" => Self::BinarySearch,
            "array.binary_search_leftmost" => Self::BinarySearchLeftmost,
            "array.binary_search_rightmost" => Self::BinarySearchRightmost,
            "array.abs" => Self::Abs,
            "array.min" => Self::Min,
            "array.max" => Self::Max,
            "array.sum" => Self::Sum,
            "array.avg" => Self::Avg,
            "array.range" => Self::Range,
            "array.median" => Self::Median,
            "array.mode" => Self::Mode,
            "array.percentile_nearest_rank" => Self::PercentileNearestRank,
            "array.percentile_linear_interpolation" => Self::PercentileLinearInterpolation,
            "array.percentrank" => Self::PercentRank,
            "array.covariance" => Self::Covariance,
            "array.standardize" => Self::Standardize,
            "array.variance" => Self::Variance,
            "array.stdev" => Self::Stdev,
            "array.sort" => Self::Sort,
            "array.sort_indices" => Self::SortIndices,
            "array.reverse" => Self::Reverse,
            "array.join" => Self::Join,
            "array.clear" => Self::Clear,
            _ => return None,
        })
    }
}
