//! Immutable TA operation selection; argument and overload semantics stay in the kernels.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub(crate) enum TaOpcode {
    Sma,
    Ema,
    Dema,
    Tema,
    Rma,
    Rsi,
    Rci,
    Macd,
    Tsi,
    Cmo,
    Cci,
    Cog,
    Ao,
    Bop,
    Bb,
    Bbw,
    Kc,
    Kcw,
    PivotHigh,
    PivotLow,
    PivotPointLevels,
    Cum,
    Max,
    Min,
    Stdev,
    Variance,
    Range,
    Dev,
    Vwap,
    Vwma,
    Mfi,
    Wma,
    Hma,
    Swma,
    Alma,
    Linreg,
    Stoch,
    Wpr,
    Correlation,
    Covariance,
    Median,
    Mode,
    PercentileNearestRank,
    PercentileLinearInterpolation,
    Percentrank,
    Tr,
    Atr,
    Supertrend,
    Dmi,
    Sar,
    Change,
    Mom,
    Roc,
    Rising,
    Falling,
    BarsSince,
    ValueWhen,
    Cross,
    Crossover,
    Crossunder,
    Highest,
    Lowest,
    HighestBars,
    LowestBars,
}

impl TaOpcode {
    pub(crate) fn for_name(callee: &str) -> Option<Self> {
        Some(match callee {
            "ta.sma" => Self::Sma,
            "ta.ema" => Self::Ema,
            "ta.dema" => Self::Dema,
            "ta.tema" => Self::Tema,
            "ta.rma" => Self::Rma,
            "ta.rsi" => Self::Rsi,
            "ta.rci" => Self::Rci,
            "ta.macd" => Self::Macd,
            "ta.tsi" => Self::Tsi,
            "ta.cmo" => Self::Cmo,
            "ta.cci" => Self::Cci,
            "ta.cog" => Self::Cog,
            "ta.ao" => Self::Ao,
            "ta.bop" => Self::Bop,
            "ta.bb" => Self::Bb,
            "ta.bbw" => Self::Bbw,
            "ta.kc" => Self::Kc,
            "ta.kcw" => Self::Kcw,
            "ta.pivothigh" => Self::PivotHigh,
            "ta.pivotlow" => Self::PivotLow,
            "ta.pivot_point_levels" => Self::PivotPointLevels,
            "ta.cum" => Self::Cum,
            "ta.max" => Self::Max,
            "ta.min" => Self::Min,
            "ta.stdev" => Self::Stdev,
            "ta.variance" => Self::Variance,
            "ta.range" => Self::Range,
            "ta.dev" => Self::Dev,
            "ta.vwap" => Self::Vwap,
            "ta.vwma" => Self::Vwma,
            "ta.mfi" => Self::Mfi,
            "ta.wma" => Self::Wma,
            "ta.hma" => Self::Hma,
            "ta.swma" => Self::Swma,
            "ta.alma" => Self::Alma,
            "ta.linreg" => Self::Linreg,
            "ta.stoch" => Self::Stoch,
            "ta.wpr" => Self::Wpr,
            "ta.correlation" => Self::Correlation,
            "ta.covariance" => Self::Covariance,
            "ta.median" => Self::Median,
            "ta.mode" => Self::Mode,
            "ta.percentile_nearest_rank" => Self::PercentileNearestRank,
            "ta.percentile_linear_interpolation" => Self::PercentileLinearInterpolation,
            "ta.percentrank" => Self::Percentrank,
            "ta.tr" => Self::Tr,
            "ta.atr" => Self::Atr,
            "ta.supertrend" => Self::Supertrend,
            "ta.dmi" => Self::Dmi,
            "ta.sar" => Self::Sar,
            "ta.change" => Self::Change,
            "ta.mom" => Self::Mom,
            "ta.roc" => Self::Roc,
            "ta.rising" => Self::Rising,
            "ta.falling" => Self::Falling,
            "ta.barssince" => Self::BarsSince,
            "ta.valuewhen" => Self::ValueWhen,
            "ta.cross" => Self::Cross,
            "ta.crossover" => Self::Crossover,
            "ta.crossunder" => Self::Crossunder,
            "ta.highest" => Self::Highest,
            "ta.lowest" => Self::Lowest,
            "ta.highestbars" => Self::HighestBars,
            "ta.lowestbars" => Self::LowestBars,
            _ => return None,
        })
    }
}
