struct NamedStringConstant {
    name: &'static str,
    value: &'static str,
}

const NAMED_STRING_CONSTANTS: &[NamedStringConstant] = &[
    same_string_constant("shape.xcross"),
    same_string_constant("shape.cross"),
    same_string_constant("shape.circle"),
    same_string_constant("shape.triangleup"),
    same_string_constant("shape.triangledown"),
    same_string_constant("shape.flag"),
    same_string_constant("shape.arrowup"),
    same_string_constant("shape.arrowdown"),
    same_string_constant("shape.square"),
    same_string_constant("shape.diamond"),
    same_string_constant("shape.labelup"),
    same_string_constant("shape.labeldown"),
    same_string_constant("location.abovebar"),
    same_string_constant("location.belowbar"),
    same_string_constant("location.top"),
    same_string_constant("location.bottom"),
    same_string_constant("location.absolute"),
    same_string_constant("plot.style_line"),
    same_string_constant("plot.linestyle_solid"),
    same_string_constant("plot.linestyle_dotted"),
    same_string_constant("plot.linestyle_dashed"),
    same_string_constant("plot.style_stepline"),
    same_string_constant("plot.style_stepline_diamond"),
    same_string_constant("plot.style_histogram"),
    same_string_constant("plot.style_cross"),
    same_string_constant("plot.style_area"),
    same_string_constant("plot.style_columns"),
    same_string_constant("plot.style_circles"),
    same_string_constant("plot.style_linebr"),
    same_string_constant("plot.style_areabr"),
    same_string_constant("hline.style_solid"),
    same_string_constant("hline.style_dotted"),
    same_string_constant("hline.style_dashed"),
    same_string_constant("xloc.bar_index"),
    same_string_constant("xloc.bar_time"),
    same_string_constant("yloc.price"),
    same_string_constant("yloc.abovebar"),
    same_string_constant("yloc.belowbar"),
    same_string_constant("label.style_none"),
    same_string_constant("label.style_xcross"),
    same_string_constant("label.style_cross"),
    same_string_constant("label.style_triangleup"),
    same_string_constant("label.style_triangledown"),
    same_string_constant("label.style_flag"),
    same_string_constant("label.style_circle"),
    same_string_constant("label.style_square"),
    same_string_constant("label.style_diamond"),
    same_string_constant("label.style_arrowup"),
    same_string_constant("label.style_arrowdown"),
    same_string_constant("label.style_label_up"),
    same_string_constant("label.style_label_down"),
    same_string_constant("label.style_label_left"),
    same_string_constant("label.style_label_right"),
    same_string_constant("label.style_label_lower_left"),
    same_string_constant("label.style_label_lower_right"),
    same_string_constant("label.style_label_upper_left"),
    same_string_constant("label.style_label_upper_right"),
    same_string_constant("label.style_label_center"),
    same_string_constant("line.style_solid"),
    same_string_constant("line.style_dotted"),
    same_string_constant("line.style_dashed"),
    same_string_constant("line.style_arrow_left"),
    same_string_constant("line.style_arrow_right"),
    same_string_constant("line.style_arrow_both"),
    same_string_constant("extend.none"),
    same_string_constant("extend.right"),
    same_string_constant("extend.left"),
    same_string_constant("extend.both"),
    same_string_constant("size.auto"),
    same_string_constant("size.tiny"),
    same_string_constant("size.small"),
    same_string_constant("size.normal"),
    same_string_constant("size.large"),
    same_string_constant("size.huge"),
    same_string_constant("text.align_left"),
    same_string_constant("text.align_center"),
    same_string_constant("text.align_right"),
    same_string_constant("text.align_top"),
    same_string_constant("text.align_bottom"),
    same_string_constant("text.wrap_none"),
    same_string_constant("text.wrap_auto"),
    same_string_constant("font.family_default"),
    same_string_constant("font.family_monospace"),
    same_string_constant("position.top_left"),
    same_string_constant("position.top_center"),
    same_string_constant("position.top_right"),
    same_string_constant("position.middle_left"),
    same_string_constant("position.middle_center"),
    same_string_constant("position.middle_right"),
    same_string_constant("position.bottom_left"),
    same_string_constant("position.bottom_center"),
    same_string_constant("position.bottom_right"),
    same_string_constant("display.all"),
    same_string_constant("display.none"),
    same_string_constant("display.pane"),
    same_string_constant("display.price_scale"),
    same_string_constant("display.status_line"),
    same_string_constant("display.data_window"),
    same_string_constant("display.pine_screener"),
    same_string_constant("barmerge.gaps_off"),
    same_string_constant("barmerge.gaps_on"),
    same_string_constant("barmerge.lookahead_off"),
    same_string_constant("barmerge.lookahead_on"),
    same_string_constant("scale.left"),
    same_string_constant("scale.right"),
    same_string_constant("scale.none"),
    same_string_constant("alert.freq_all"),
    same_string_constant("alert.freq_once_per_bar"),
    same_string_constant("alert.freq_once_per_bar_close"),
    same_string_constant("format.inherit"),
    same_string_constant("format.mintick"),
    same_string_constant("format.price"),
    same_string_constant("format.percent"),
    same_string_constant("format.volume"),
    NamedStringConstant {
        name: "adjustment.dividends",
        value: "dividends",
    },
    NamedStringConstant {
        name: "adjustment.none",
        value: "none",
    },
    NamedStringConstant {
        name: "adjustment.splits",
        value: "splits",
    },
    NamedStringConstant {
        name: "backadjustment.inherit",
        value: "inherit",
    },
    NamedStringConstant {
        name: "backadjustment.off",
        value: "off",
    },
    NamedStringConstant {
        name: "backadjustment.on",
        value: "on",
    },
    currency_string_constant("currency.AUD", "AUD"),
    currency_string_constant("currency.BDT", "BDT"),
    currency_string_constant("currency.BHD", "BHD"),
    currency_string_constant("currency.BRL", "BRL"),
    currency_string_constant("currency.BTC", "BTC"),
    currency_string_constant("currency.CAD", "CAD"),
    currency_string_constant("currency.CHF", "CHF"),
    currency_string_constant("currency.CLP", "CLP"),
    currency_string_constant("currency.CNY", "CNY"),
    currency_string_constant("currency.COP", "COP"),
    currency_string_constant("currency.CZK", "CZK"),
    currency_string_constant("currency.DKK", "DKK"),
    currency_string_constant("currency.EGP", "EGP"),
    currency_string_constant("currency.ETH", "ETH"),
    currency_string_constant("currency.EUR", "EUR"),
    currency_string_constant("currency.GBP", "GBP"),
    currency_string_constant("currency.HKD", "HKD"),
    currency_string_constant("currency.HUF", "HUF"),
    currency_string_constant("currency.IDR", "IDR"),
    currency_string_constant("currency.ILS", "ILS"),
    currency_string_constant("currency.INR", "INR"),
    currency_string_constant("currency.ISK", "ISK"),
    currency_string_constant("currency.JPY", "JPY"),
    currency_string_constant("currency.KES", "KES"),
    currency_string_constant("currency.KRW", "KRW"),
    currency_string_constant("currency.KWD", "KWD"),
    currency_string_constant("currency.LKR", "LKR"),
    currency_string_constant("currency.MAD", "MAD"),
    currency_string_constant("currency.MXN", "MXN"),
    currency_string_constant("currency.MYR", "MYR"),
    currency_string_constant("currency.NGN", "NGN"),
    currency_string_constant("currency.NONE", "NONE"),
    currency_string_constant("currency.NOK", "NOK"),
    currency_string_constant("currency.NZD", "NZD"),
    currency_string_constant("currency.PEN", "PEN"),
    currency_string_constant("currency.PHP", "PHP"),
    currency_string_constant("currency.PKR", "PKR"),
    currency_string_constant("currency.PLN", "PLN"),
    currency_string_constant("currency.QAR", "QAR"),
    currency_string_constant("currency.RON", "RON"),
    currency_string_constant("currency.RSD", "RSD"),
    currency_string_constant("currency.RUB", "RUB"),
    currency_string_constant("currency.SAR", "SAR"),
    currency_string_constant("currency.SEK", "SEK"),
    currency_string_constant("currency.SGD", "SGD"),
    currency_string_constant("currency.THB", "THB"),
    currency_string_constant("currency.TND", "TND"),
    currency_string_constant("currency.TRY", "TRY"),
    currency_string_constant("currency.TWD", "TWD"),
    currency_string_constant("currency.USD", "USD"),
    currency_string_constant("currency.USDT", "USDT"),
    currency_string_constant("currency.VES", "VES"),
    currency_string_constant("currency.VND", "VND"),
    currency_string_constant("currency.ZAR", "ZAR"),
    same_string_constant("order.ascending"),
    same_string_constant("order.descending"),
    same_string_constant("strategy.fixed"),
    same_string_constant("strategy.cash"),
    same_string_constant("strategy.percent_of_equity"),
    same_string_constant("strategy.long"),
    same_string_constant("strategy.short"),
    same_string_constant("strategy.direction.all"),
    same_string_constant("strategy.direction.long"),
    same_string_constant("strategy.direction.short"),
    same_string_constant("strategy.oca.cancel"),
    same_string_constant("strategy.oca.none"),
    same_string_constant("strategy.oca.reduce"),
    same_string_constant("strategy.commission.cash_per_contract"),
    same_string_constant("strategy.commission.cash_per_order"),
    same_string_constant("strategy.commission.percent"),
    NamedStringConstant {
        name: "session.extended",
        value: "extended",
    },
    NamedStringConstant {
        name: "session.regular",
        value: "regular",
    },
    NamedStringConstant {
        name: "settlement_as_close.inherit",
        value: "inherit",
    },
    NamedStringConstant {
        name: "settlement_as_close.off",
        value: "off",
    },
    NamedStringConstant {
        name: "settlement_as_close.on",
        value: "on",
    },
    NamedStringConstant {
        name: "syminfo.basecurrency",
        value: "USD",
    },
    NamedStringConstant {
        name: "syminfo.currency",
        value: "USD",
    },
    NamedStringConstant {
        name: "syminfo.description",
        value: "Apple Inc.",
    },
    NamedStringConstant {
        name: "syminfo.country",
        value: "US",
    },
    NamedStringConstant {
        name: "syminfo.industry",
        value: "Telecommunications Equipment",
    },
    NamedStringConstant {
        name: "syminfo.main_tickerid",
        value: "NASDAQ:AAPL",
    },
    NamedStringConstant {
        name: "syminfo.prefix",
        value: "NASDAQ",
    },
    NamedStringConstant {
        name: "syminfo.root",
        value: "AAPL",
    },
    NamedStringConstant {
        name: "syminfo.session",
        value: "regular",
    },
    NamedStringConstant {
        name: "syminfo.sector",
        value: "Electronic Technology",
    },
    NamedStringConstant {
        name: "syminfo.ticker",
        value: "AAPL",
    },
    NamedStringConstant {
        name: "syminfo.tickerid",
        value: "NASDAQ:AAPL",
    },
    NamedStringConstant {
        name: "syminfo.timezone",
        value: "Etc/UTC",
    },
    NamedStringConstant {
        name: "syminfo.type",
        value: "stock",
    },
    NamedStringConstant {
        name: "syminfo.volumetype",
        value: "base",
    },
];

const fn same_string_constant(name: &'static str) -> NamedStringConstant {
    NamedStringConstant { name, value: name }
}

const fn currency_string_constant(name: &'static str, value: &'static str) -> NamedStringConstant {
    NamedStringConstant { name, value }
}

#[must_use]
pub fn named_string_constant(name: &str) -> Option<&'static str> {
    NAMED_STRING_CONSTANTS
        .iter()
        .find(|constant| constant.name == name)
        .map(|constant| constant.value)
}

pub(crate) fn named_string_constant_names() -> impl Iterator<Item = &'static str> {
    NAMED_STRING_CONSTANTS.iter().map(|constant| constant.name)
}
