[package]
name = "pine-sema"
version = "0.3.0-rc.1"
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pine-builtins = { path = "../pine-builtins" }
pine-ir = { path = "../pine-ir" }
pine-syntax = { path = "../pine-syntax" }

[lib]
name = "pine_sema"
path = "src/lib.rs"
