//@version=6
strategy("Host quantity precision",initial_capital=40450,margin_long=50,margin_short=50)
if bar_index==0
    strategy.entry("Long",strategy.long,qty=1)
if bar_index==2
    strategy.close_all()
plot(syminfo.mincontract,"minimum contract")
plot(strategy.position_size,"position")
plot(strategy.netprofit,"net profit")
plot(strategy.margin_liquidation_price,"liquidation price")
plot(strategy.closedtrades,"closed trades")
plot(strategy.closedtrades.size(0),"first size")
plot(strategy.closedtrades.size(1),"second size")
